export const presetProfiles = {
  normal: {
    spacing: "10",
    blur: "0",
    brightness: "100",
    contrast: "100",
    grayscale: "0",
    invert: "0",
    sepia: "0",
    saturate: "100",
    hueMinusRotate: "0",
    opacity: "100",
    base: "#ffc600",
  },

  vintage: {
    spacing: "15",
    blur: "1",
    brightness: "110",
    contrast: "90",
    grayscale: "0",
    invert: "0",
    sepia: "60",
    saturate: "130",
    hueMinusRotate: "20",
    opacity: "100",
    base: "#cfb97e",
  },

  noir: {
    spacing: "10",
    blur: "0",
    brightness: "90",
    contrast: "150",
    grayscale: "100",
    invert: "0",
    sepia: "10",
    saturate: "0",
    hueMinusRotate: "0",
    opacity: "100",
    base: "#ffffff",
  },

  sepia: {
    spacing: "18",
    blur: "1",
    brightness: "100",
    contrast: "95",
    grayscale: "0",
    invert: "0",
    sepia: "100",
    saturate: "90",
    hueMinusRotate: "0",
    opacity: "100",
    base: "#e6dfcc",
  },

  neon: {
    spacing: "16",
    blur: "1",
    brightness: "115",
    contrast: "130",
    grayscale: "0",
    invert: "0",
    sepia: "0",
    saturate: "250",
    hueMinusRotate: "290",
    opacity: "100",
    base: "#ff007f",
  },

  edgy: {
    spacing: "20",
    blur: "0",
    brightness: "80",
    contrast: "200",
    grayscale: "100",
    invert: "0",
    sepia: "0",
    saturate: "100",
    hueMinusRotate: "0",
    opacity: "100",
    base: "#1a1a1a",
  },

  punchyCool: {
    spacing: "10",
    blur: "0",
    brightness: "105",
    contrast: "125",
    grayscale: "0",
    invert: "0",
    sepia: "0",
    saturate: "140",
    hueMinusRotate: "190",
    opacity: "100",
    base: "#00d2ff",
  },

  punchyWarm: {
    spacing: "10",
    blur: "0",
    brightness: "105",
    contrast: "125",
    grayscale: "0",
    invert: "0",
    sepia: "15",
    saturate: "150",
    hueMinusRotate: "15",
    opacity: "100",
    base: "#ff9900",
  },

  blackAndWhite: {
    spacing: "14",
    blur: "0",
    brightness: "100",
    contrast: "110",
    grayscale: "100",
    invert: "0",
    sepia: "0",
    saturate: "0",
    hueMinusRotate: "0",
    opacity: "100",
    base: "#cccccc",
  },

  redPink: {
    spacing: "10",
    blur: "0",
    brightness: "110",
    contrast: "120",
    grayscale: "0",
    invert: "0",
    sepia: "0",
    saturate: "160",
    hueMinusRotate: "330",
    opacity: "100",
    base: "#ffb6c1",
  },

  greenYellow: {
    spacing: "10",
    blur: "0",
    brightness: "105",
    contrast: "115",
    grayscale: "0",
    invert: "0",
    sepia: "0",
    saturate: "150",
    hueMinusRotate: "85",
    opacity: "100",
    base: "#a6ff00",
  },

  bluePurple: {
    spacing: "10",
    blur: "0",
    brightness: "95",
    contrast: "125",
    grayscale: "0",
    invert: "0",
    sepia: "0",
    saturate: "170",
    hueMinusRotate: "250",
    opacity: "100",
    base: "#7000ff",
  },

  tealOrange: {
    spacing: "10",
    blur: "0",
    brightness: "100",
    contrast: "135",
    grayscale: "0",
    invert: "0",
    sepia: "10",
    saturate: "160",
    hueMinusRotate: "145",
    opacity: "100",
    base: "#ff6b35",
  },

  blurred: {
    spacing: "10",
    blur: "10",
    brightness: "100",
    contrast: "100",
    grayscale: "0",
    invert: "0",
    sepia: "0",
    saturate: "100",
    hueMinusRotate: "0",
    opacity: "100",
    base: "#ffc600",
  },
};
